### ISSUE TITLE
Placement of language selector on mobile version needs to be properly designed or themed

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#106]

**Comment by cynthialee** [comment]
Selector still needs some tweaking on mobile. Height doesn't match filter bar.

**Comment by PeaceGeeks** [comment]
see #120 for screenshot.

**Comment by lkysow** [comment]
Fixed in #143

**Comment by PeaceGeeks** [comment]
Hi guys - this is still not fixed on my devices. 
![img_3697](https://cloud.githubusercontent.com/assets/2263033/8818896/ff6660c4-301c-11e5-9b73-3a84a770ddf5.PNG)

**Comment by lkysow** [comment]
@PeaceGeeks you need to wait for me to upload the new changes. I mark the issue as closed while I'm working to merge, then once I'm done for the night I push to the dev site. Please check now.

**Comment by PeaceGeeks** [comment]
Ok - year I realized that just before you emailed. Thanks. This is better. It still overlaps with the white bar, but at least I can see both language options in the drop down now. 
![img_3699](https://cloud.githubusercontent.com/assets/2263033/8819690/c1ecc6cc-3024-11e5-900f-74617a075595.PNG)

I will close this for now, and open a low priority theming one for later.
