### ISSUE TITLE
Show Details for individual service records not clicking thru on mobile

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#91]

**Comment by cynthialee** [comment]
@PeaceGeeks Are you talking about "show details" when you click on a pin on a map, as seen below? It works for me, although I had to mess around to even show the map.  @tuckerbuchy @lkysow @Jareechang Can you guys verify the mobile view in general is broken, e.g. can't see map, parts are hidden?

![image](https://cloud.githubusercontent.com/assets/3262577/8514530/56a19d2e-2346-11e5-8aff-03b068e2f2f0.png)

**Comment by PeaceGeeks** [comment]
@cynthialee - do you mean loading the page? Yes I have found that I have to re-load sometimes 2 or 3 times before the site loads up

**Comment by cynthialee** [comment]
Spoke with Renee, she wasn't sure what this ticket is about. Closing.

**Comment by PeaceGeeks** [comment]
![img_3674](https://cloud.githubusercontent.com/assets/2263033/8515104/0b2badca-2351-11e5-8e41-8099f8138e76.jpg)
![img_3672](https://cloud.githubusercontent.com/assets/2263033/8515105/0b2ed9be-2351-11e5-90cb-b6d7d93a9dcd.jpg)
![img_3673](https://cloud.githubusercontent.com/assets/2263033/8515106/0b305e10-2351-11e5-89cd-12ceeee8b00a.jpg)

**Comment by PeaceGeeks** [comment]
![img_3675](https://cloud.githubusercontent.com/assets/2263033/8515224/6f34a252-2353-11e5-88c0-bbbcd10c57c1.jpg)

**Comment by PeaceGeeks** [comment]
First this last screeshot, i can't scroll beyond that point
i ca see that there is text, but it won't let me scroll past this. 
1) go to site
2) filter on cash assitance
3) choose mercy corps (first option)
4) scroll

**Comment by PeaceGeeks** [comment]
can't get through to map view (#107) but when I do by mistake, 
1) i click on a marker to display the preview
2) click on 'Show Details' 
Nothing happens.

**Comment by PeaceGeeks** [comment]
Click through to individual record - the service labels appear but not the corresponding content. 
![img_3676](https://cloud.githubusercontent.com/assets/2263033/8515298/e3e3882e-2354-11e5-8b54-c33f6ca673ec.jpg)

**Comment by cynthialee** [comment]
Looks like this has been resolved in the latest code. After deploying to website, revisit this ticket. In general, the issues are:
- specific service's details are not loading
- content seems to be cut off, cannot scroll for more

**Comment by cynthialee** [comment]
@PeaceGeeks Can you retest this? It works for me.

**Comment by PeaceGeeks** [comment]
@cynthialee - i can't test - still having the issue of the map not fully displaying despite clearing my browser history

**Comment by PeaceGeeks** [comment]
still a bit buggy but good enough for now. will open a new ticket.
